shallow_clone: true

environment:
  matrix:
  - LUA: "lua=5.1"
  - LUA: "lua=5.2"
  - LUA: "lua=5.3"
  - LUA: "luajit=2.0"
  - LUA: "luajit=2.1"

configuration:
  - vs08_32
  - vs_64
  - mingw

install:
  - set PATH=C:\Python27\Scripts;C:\MinGW\bin;%PATH%
  - pip install hererocks
  - hererocks lua_install --%LUA% --target %configuration% -r latest
  - call lua_install\bin\activate
  - git clone --depth=1 https://github.com/keplerproject/luacov
  - cd luacov && luarocks make && cd ..
  - luarocks install busted

build_script:
  - luarocks make --deps-mode=none

test_script:
  - busted
  - busted -C luacov
